apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:masters
      rolearn: arn:aws:iam::954744412580:role/UdacityFlaskDeployCBKubectlRole
      username: build 
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::954744412580:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1F0N6YEQ9XAGA
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
metadata:
  creationTimestamp: "2021-08-17T22:54:36Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1167"
  uid: 1f6c4f1d-c81d-4156-ab59-fcfe570c2aad
